- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    http_domain: "{{ ansible_eth1.ipv4.address }}.xip.io"
    http_username: bosun
    http_password: "{{ lookup('password', 'bosun.passwd chars=letters,digits length=8') }}"
  roles:
  - role: bosunstack
    tags: bosunstack
  - role: bosunstack-init
    tags: bosunstack-init
  tasks:
  - debug:
      msg: "Bosun running at http://{{ http_domain }}/ login: {{ http_username }} password: {{ http_password }}"
