- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    http_domain: "{{ ansible_eth1.ipv4.address }}.xip.io"
    http_username: bosun
    http_password: "{{ lookup('password', 'bosun.passwd chars=letters,digits length=8') }}"
  roles:
  - role: bosunstack
    tags: bosunstack
  tasks:
  - name: Create OpenTSDB tables
    command: ./share/opentsdb/tools/create_table.sh chdir={{ home }}/bosun/opentsdb creates={{ home }}/bosun/data/hbase/data/default/tsdb
    environment:
      HBASE_HOME: "{{ home }}/bosun/hbase"
      COMPRESSION: lzo
    tags: opentsdb-init
  - debug:
      msg: "Bosun running at http://{{ http_domain }}/ login: {{ http_username }} password: {{ http_password }}"
